# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          
    - jekyll-paginate
    - jekyll-gist

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Bhavya Karia'
tagline:          'Bhavya Karia'
description:      'Developing scalable products'
url:              http://hyde.getpoole.com
baseurl:          /bhavyakaria.github.io

author:
  name:           'Bhavya Karia'
  url:            https://twitter.com/bhavyankaria

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bhavyakaria
